spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/transaction
    username: root
    password: Danish@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  
server:
  port: 8083
